package com.myanimelist.entity;

import lombok.*;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * A new feature has been added - the ability to add anime to tabs like `viewed`, `favorites`, etc.
 * The reason for this is that the application should have a separate tab to view all anime
 * by certain parameters such as `dropped`. To display information for each anime,
 * multiple requests to the JikanAPI would be required.
 * <p>
 * However, the JikanAPI server only allows for three requests per second. To mitigate this issue,
 * a new entity has been created in the database to store minimal information about each anime
 * (id and title) that has been added to tabs like `viewed`, etc.
 * <p>
 * The list of favorite anime will be retrieved from the database, but additional details will be
 * obtained from the JikanAPI based on user requests. The database will only store the id and name of
 * the anime and will not store any extra information.
 */

@Data
@ToString(exclude = "userAnimeList")
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table
public class Anime implements BaseEntity<Integer> {

    /**
     * This field is not generated by this application but rather retrieved from an external API.
     * Therefore, no @GeneratedValue annotation is used.
     */
    @Id
    private Integer id;

    private String title;
    private String image;

    @Builder.Default
    @OneToMany(
            mappedBy = "anime",
            fetch = FetchType.LAZY,
            cascade = {
                    CascadeType.DETACH,
                    CascadeType.MERGE,
                    CascadeType.PERSIST,
                    CascadeType.REFRESH
            })
    private List<UserAnime> userAnimeList = new ArrayList<>();
}
